BookKitty/BookKitty-iOS

BookKitty/BookKitty.xcodeproj/project.pbxproj, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/WidthFixedImageView.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Extension/String+Extensions.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Extension/UIView+Extensions.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Theme/Vars.swift, BookKitty/BookKitty/Source/DesignSample/ImageSampleViewController.swift, BookKitty/BookKitty/Source/DesignSample/LabelSample2ViewController.swift
- loadAsyncImage 함수 관련 Sendable 버그 수정
- 높이 고정값 수치를 추가함에 따라 컴포넌트 수정
- 기타 상수값 추가
- 책장 관련 그림자 효과 추가
- 버그 열심히 수정하였습니다. 
- 자잘한 변경 외에 튜터님 도움을 받아 버그 수정한 정도라 특별히 포인트가 될 곳은 없습니다.
=> [Feat] Image 관련 버그 수정 및 고정 높이값 추가

BookKitty/BookKitty/BookMatchKit/Tests/BookMatchKitTests/BookMatchKitTests.swift
BookMatchKit 타겟에 포함되었던 테스트 파일을 api 키 정보 제거한 상태로 추가하여, 컴파일 에러를 해결하였습니다.
=> [Fix] test 파일 추가

BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift, BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryCell.swift, BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift, BookKitty/BookKitty/Source/Repository/MockQuestionHistoryRepository.swift
- QuestionHistoryViewController 
- 구현 완료
- ViewModel과 통신하는 3개 Observable들 모두 정상적으로 이벤트 발생시키고 통신하는 것 확인
- FixedHeightImageView
- setRadius 메서드 수정
- ambiguous constraints 에러 해결 위해, equalTo로 대체
- ConfigureCell 방식은 Legacy로 승용님 업데이트 이후, 팔로업하겠습니다
=> [Feat] QuestionHistoryViewController 구현

BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIButton/RoundButton.swift, BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift, BookKitty/BookKitty/Source/Feature/NewQuestion/View/QuestionTextView.swift, BookKitty/BookKitty/Source/Feature/NewQuestion/ViewModel/NewQuestionViewModel.swift
- 질문 입력 ViewController 구현
- 커스텀 UITextView 구현
- placeholder, textCount 동기화
https://github.com/user-attachments/assets/be67d9e1-2b9d-4c6e-a780-c5e7274a4579
=> [Feat] NewQuestionViewController 구현

BookKitty/BookKitty/BookMatchKit/Package.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/BookMatchable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/BookRecommendable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/ImageSimilarityCalculatable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/SimilarityCalculatable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategy.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategyWithNoParenthesis.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift, BookKitty/BookKitty/BookMatchKit/Tests/BookMatchKitTests/BookMatchKitTests.swift
- 아래 라이브러리에 RxSwift 일괄 적용
- `BookMatchKit`
- `BookMatchCore`
- `BookMatchAPI`
- `BookMatchStrategy`
- BookMatchCore 내부 OwnedBook 구조체 최상위 모듈에서 re-export하여 패키지 외부에서 접근이 가능토록 하였습니다.
- SRP원칙을 준수하기 위해 BookMatchKit에서 도서 추천 로직을 BookRecommendationKit로 분리하였습니다.
- API 키 정보를 인자에 전달하여 인스턴스 생성이 가능토록 구조를 변경하였습니다.
진짜 async/await가 얼마나 편한 비동기 처리방식이였는지 뼈저리게 느꼈습니다. 간만에 삽질 진득하게 했습니다.
로직 복잡도로 인해 아래 모듈은 MVP 출시 이후 RxSwift 변환 진행토록 하겠습니다.
- `BookMatchRecommendationKit`
=> [Feat] BookMatchKit 고도화

BookKitty/BookKitty/BookMatchKit/Package.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ChatGPTEndpoint.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ImageDownloadEndpoint.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/NaverBooksEndpoint.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
승용님의 네트워크 패키지를 사용하여 동시성 에러를 해결하였습니다.
=> [Fix] Sendable 관련 오류 수정

BookKitty/BookKitty/Source/Feature/QuestionDetail/View/QuestionDetailViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
- 누락되었던 네비게이션 관련 옵저버블을 구현했습니다.
=> [Feat] 누락된 네비게이션 관련 옵저버블 구현

BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift, BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift, BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift, BookKitty/BookKitty/Source/Feature/Home/ViewModel/HomeViewModel.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
=> [Feat] 홈화면 구현

BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ChatGPTEndpoint.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/NaverBooksEndpoint.swift, BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
- 네트워크 호출 에러 수정
- 홈화면 저작권 텍스트 추가
=> [Fix] Network 에러 수정 및 홈화면에 저작권 텍스트 추가

BookKitty/BookKitty/Source/Persistence/BookQALinkCoreDataManager.swift, BookKitty/BookKitty/Source/Persistence/QuestionAnswerCoreDataManager.swift, BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
- 질문답변 관련 data layer 구현 완료.
- 빌드 성공 후 푸시하지만, 정작 개별 함수 동작이 제대로 이루어질지는 체크 부탁드립니다.
=> [Feat] 코어데이터 및 레포지토리 작업 완료

BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ChatGPTEndpoint.swift, BookKitty/BookKitty/Source/Common/Environment.swift, BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/AppCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/BookCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/Coordinator.swift, BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/Protocol/CoordinatorFinishDelegate.swift, BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/TabBarCoordinator.swift, BookKitty/BookKitty/Source/Feature/BookDetail/ViewModel/BookDetailViewModel.swift, BookKitty/BookKitty/Source/Feature/TabBar/View/TabBarController.swift
=> [Feat] 코디네이터 수정 및 xcconfig 사용

BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift, BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift, BookKitty/BookKitty/Source/Feature/Common/CustomNavigationBar.swift, BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionDetail/View/QuestionDetailViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
* 공통으로 사용되면 CustomNavigationBar 구현
* 기존 navigationBar 교체 
* 공통으로 사용되는 UI라 Feature/Common에 배치했습니다.
* MVP 이후 컴포넌트화 고려
=> [Feat] CustomNavigationBar 구현

BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift, BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift, BookKitty/BookKitty/Source/Feature/Home/ViewModel/HomeViewModel.swift
- viewWillAppear에서 매번 최신 데이터 가져오도록 구현
- 추후 추천 패키지 이용하는 로직으로 리팩토링 필요
| 스크린샷 |
| -- |
|<img src="https://github.com/user-attachments/assets/72043f61-d829-4f54-aacd-877282a1d3c9" width=300>|
=> [Feat] 홈 뷰에서 최근 추천받은 책 목록 보여주기 구현

BookKitty/BookKitty/Source/Common/Utility/DateFormatHandler.swift, BookKitty/BookKitty/Source/Common/Utility/NumberFormatHandler.swift, BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailInfoView.swift, BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift, BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
* BookDeatilVC에서 보여지는 가격, 출판 날짜 포맷터 구현
* NewQuestionVC에서 사용자로부터 작성되는 질문 글자 수 최소 10글자 이상으로 수정
https://github.com/user-attachments/assets/209775d6-2ef6-4ba2-8feb-ae7386ce321b
=> [Refactor] BookDeatil 데이터 포맷터, NewQuestion 질문 최소 글자 수 적용

BookKitty/BookKitty/Source/Feature/AddBook/View/BaseCameraViewController.swift
VNRecognizeTextRequest의 recognitionLanguages를 ["ko", "en"]으로 설정하여 한국어와 영어를 지원.
주석 변경
=> ocr upgrade

BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift, BookKitty/BookKitty/Source/Persistence/BookCoreDataManager.swift, BookKitty/BookKitty/Source/Persistence/BookQALinkCoreDataManager.swift, BookKitty/BookKitty/Source/Persistence/CoreDataStack.swift, BookKitty/BookKitty/Source/Persistence/Protocol/BookCoreDataManageable.swift, BookKitty/BookKitty/Source/Repository/LocalBookRepository.swift, BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift
- 책 중복 저장문제 해결
- 질문답변 목록 가져오기 에러 수정
=> [Fix] 코어데이터 관련 에러 수정

BookKitty/BookKitty/Source/Persistence/BookCoreDataManager.swift, BookKitty/BookKitty/Source/Persistence/QuestionAnswerCoreDataManager.swift, BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift
- 질문 목록도 전체 가져오기 기능 추가
- 질문 내의 책 목록이 다음과 같이 정렬됩니다. 
+ 소유한 책을 우선으로 보여줍니다.
+ 같은 소유 상태일 경우 이름 오름차순으로 보여줍니다.
=> [Feat] 질문 목록 전체 가져오기 기능 외

BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift, BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift, BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift, BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift, BookKitty/BookKitty/Source/Feature/ReviewAddBook/View/ReviewAddBookViewController.swift, BookKitty/BookKitty/Source/Feature/ReviewAddBook/ViewModel/ReviewAddBookViewModel.swift
=> feat:ocr debug

BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Extensions/UIImage+.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
=> [Fix] OCR 로직 연결 문제 해결 (#66)

BookKitty/BookKitty/App/Base.lproj/LaunchScreen.storyboard, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/Endpoint/ImageDownloadEndpoint.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift, BookKitty/BookKitty/NetworkKit/Sources/NetworkKit/NetworkManager.swift, BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
- 런치 스크린 파일을 작성하였습니다.
| 임시 런치 스크린 |
| -- |
|<img src="https://github.com/user-attachments/assets/afa2c060-0d95-434f-8243-4f41cf6bea1f" width=300>|
- 임시로 텍스트만 넣어놨어용
- 추후 이미지로 대체하면 좋을 듯 합니다
=> [Feat] 런치 스크린 작성

BookKitty/BookKitty/Source/Common/Error/AddBookError.swift, BookKitty/BookKitty/Source/Common/Error/BookMatchError.swift, BookKitty/BookKitty/Source/Common/Model/Book.swift, BookKitty/BookKitty/Source/Common/Utility/BookKittyLogger.swift, BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift, BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift, BookKitty/BookKitty/Source/Feature/AddBook/View/LoadingCircleView.swift, BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift, BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift, BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift, BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
- 책 추가 과정에서 에러 발생 시 대응 alert 추가
- Book isOwned 기본값 제거
- 책 추가 시 책 저장 안되는 문제 해결
- 책 찾는 도중 로딩 인디케이터 구현
- 책장 찍기 문구 변경
- isOwned는 저장 상태를 나타내는 중요한 요소인데, 기본값이 들어가 있어 빼먹는 경우가 있습니다.
- 따라서 기본값을 제거해 잘못된 사용을 방지했습니다.
| 에러 1 | 에러 2 |
| -- | -- |
|<img src="https://github.com/user-attachments/assets/2b598eff-3db5-4e4f-a0a8-3b5fabbcbed0" width=300>|<img src="https://github.com/user-attachments/assets/d94c7f7a-87ae-467f-b616-6136e2bb77c3" width=300>|
| 로딩 인디케이터 |
| -- |
|<img src="https://github.com/user-attachments/assets/0c01addf-c737-4381-b924-a7a33339abed" width=300>|
- 현재 에러가 네트워크 오류임에도 모두 bookNotFound로 반환됩니다. 이에 따른 세부 처리가 필요합니당
=> [Feat] 책 추가 뷰 고도화

BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift, BookKitty/BookKitty/Source/Common/Error/AddBookError.swift, BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
- BookMatchKit에서 발생한 에러에 따라 Presentation 처리
- 현재는 대부분 알수 없는 오류로 처리합니다. BookMatchKit / BookKitty간 에러 매칭해볼 필요가 있을 것 같아요!
=> [Feat] 질문 결과 뷰 에러 처리

BookKitty/BookKitty.xcodeproj/project.pbxproj, BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
- 책이 없는 경우 구현
- 책이 있는 경우 변경된 디자인 적용
- 앱 표시 이름 책냥이로 변경
| 책이 없는 경우 | 책이 있는 경우 |
| -- | -- |
|<img src="https://github.com/user-attachments/assets/2aab8ad6-5c59-457d-b28f-e2549197bbbe" width=300>|<img src="https://github.com/user-attachments/assets/e67eedaf-9732-4ccb-9cb8-925e050ea321" width=300>|
=> [Feat] 홈뷰 책 없음 구현

BookKitty/BookKitty/Source/Feature/Common/EmptyDataDescriptionView.swift, BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
QuesitonHistoryVC, MyLibraryVC의 각 리스트 뷰 에 데이터가 없을 때 backgroundView를 통해 안내 문구 추가하였습니다.
=> [Feat] EmptyDataDescriptionView 구현"

BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
=> [Feat] 백그라운드 색상 다시 롤백

BookKitty/BookKitty.xcodeproj/project.pbxproj, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/ImageDownloadAPI.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchError/BookMatchError.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchLogger.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/BookMatchable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/ImageProcessable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/TextExtractable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Utils/ImageProcessor.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Utils/TextExtractor.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategy.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategyWithNoParenthesis.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/Protocols/SimilarityCalculatable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift, BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift, BookKitty/PrivacyInfo.xcprivacy
- BookMatchKit 내부 OCR 및 CoreML 관련 로직 RxSwift로 통일
- BookMatchLogger 에러 로그 분기처리
- OCR 로직 및 이미지 처리 로직 TextExtractor, ImageProcessor 클래스로 분리
=> [Refactor] BookMatchKit 리펙토링

BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/FlexibleImageView.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift, BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/WidthFixedImageView.swift
- 제약 충돌 방지
- setUpImage 및 setDefaultImage 내부 Width 및 Height 제약 변경 로직 일괄 변경
=> [Fix] KingFisher UIImageView 3개 높이, 너비 업데이트 로직 일괄 변경

BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Protocols/BookSearchable.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Service/BookSearchService.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookOCRKit/BookOCRKit.swift, BookKitty/BookKitty/BookMatchKit/Sources/BookOCRKit/Protocols/BookMatchable.swift
-BookOCRKit 내부 searchByText 메서드 추가
=> [Feat] Query로 책 검색결과 추가 구현

BookKitty/BookKitty/App/Base.lproj/LaunchScreen.storyboard, BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
- 스크롤 계속해서 내려가는 현상 수정하였습니다.
- 런치스크린에 background0 색상 적용하였습니다.
=> [Fix] 스크롤 계속해서 내려가는 현상 수정, 런치스크린 백그라운드 적용

BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
- 머지 충돌 제대로 해결되지 않은 부분 수정하였습니다.
=> [Fix] 머지 후 이슈 수정

BookKitty/BookKitty.xcodeproj/project.pbxproj, BookKitty/BookKitty.xcodeproj/xcshareddata/xcschemes/BookKitty.xcscheme, BookKitty/BookKitty/App/AppDelegate.swift, BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift, BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/AppCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/Protocol/Coordinator.swift, BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift, BookKitty/BookKitty/Source/Coordinator/TabBarCoordinator.swift, BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift, BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift, BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift, BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift, BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift, BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift, BookKitty/BookKitty/Source/Persistence/BookCoreDataManager.swift, BookKitty/BookKitty/Source/Persistence/Protocol/BookCoreDataManageable.swift, BookKitty/BookKitty/Source/Persistence/Protocol/QuestionAnswerCoreDataManageable.swift, BookKitty/BookKitty/Source/Persistence/QuestionAnswerCoreDataManager.swift, BookKitty/BookKitty/Source/Repository/LocalBookRepository.swift, BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift, BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift, BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift, BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift, BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift, BookKitty/GoogleService-Info.plist
* ViewDidAppear시 해당 화면 로깅
* 사용자 질물, 소유한 책 개수 로깅
* 질문에대한 책 리스트 로깅
=> [Feat] Firebase 로깅 시스템 구축
